# Site settings
title: Azizah Giwa
email: azizahgiwa@gmail.com
description: I am a Data Analyst and Project Manager proficient in SQL, Python, R, Tableau, Power BI, Asana, and Microsoft Office. > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "azizah-giwa.github.io/AzizahGiwa/" # the base hostname & protocol for your site

social:
  - title: linkedin
    url: https://www.linkedin.com/in/azizah-giwa-174953152
  - title: github
    url: https://github.com/Azizah-Giwa
  - title: tableau
    url: https://public.tableau.com/app/profile/azizah.giwa/vizzes
linkedin_username: Azizah Giwa
github_username: Azizah-Giwa

# Build settings
markdown: kramdown
